### PR TITLE
Cluster out.tips using sklearn

### LINKED ISSUE #6: Cluster using scikit-learn
### Description 
Use sklearn.cluster to cluster [out.tips](https://github.com/trvrb/antigen/blob/002f425f1e25b1f49bec307bb99b3f941e062ddd/example/out.tips) to reproduce this figure from antigen's [Mathematic notebook](https://github.com/trvrb/antigen/blob/002f425f1e25b1f49bec307bb99b3f941e062ddd/example/antigen-analysis.nb):
image

### Possible solution
Use sklearn.cluster.KMeans (where k = 11) or sklearn.cluster.AgglomerativeClustering

### PR DESCRIPTION
**Pull request by thienktran**
## Description

Used [sklearn.cluster](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.cluster).[KMeans](https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn-cluster-kmeans) to cluster out.tips. 
Also, removed csv since we're clustering with out.tips not out.timeseries. 

Closes #6 

## Tests

Compared the [output](https://github.com/matsengrp/antigen/compare/main...6-cluster-sklearn#diff-3439cbf3368d3ffd5e9c2487e65dd35eb1c77cc19f7f33f7557569dcb5929105) produced by [clustering.py](https://github.com/matsengrp/antigen/compare/main...6-cluster-sklearn#diff-61b89a184825c2c5ffb7bf2683cf09ba39678e8e45cd06becc1b11f905cc35b5) with Trevor's [Mathematica clustering](https://github.com/matsengrp/antigen/compare/main...6-cluster-sklearn#diff-3439cbf3368d3ffd5e9c2487e65dd35eb1c77cc19f7f33f7557569dcb5929105).

## Checklist:

* [x] The code uses informative and accurate variable and function names
* [x] The functionality is factored out into functions and methods with logical interfaces
* [x] Comments are up to date, document intent, and there are no commented-out code blocks
* [x] Commenting and/or documentation is sufficient for others to be able to understand intent and implementation
* [x] TODOs have been eliminated from the code
* [x] The corresponding issue number (e.g. `#6`) has been searched for in the code to find relevant notes
* [ ] Documentation has been redeployed

### CODE REVIEW

File: Simulation.java [hunk 1]
```diff
@@ -475,29 +474,6 @@ public void run() {
 			
 		}
 	}
-
-	public void writeDataCSV() throws FileNotFoundException {
```
Comment (zorian15) [inline Simulation.java:479]: Any reason we're deleting this method? Was it not needed to perform your clustering?

File: clustering.py [hunk 2]
```diff
@@ -0,0 +1,36 @@
+# import libraries
+import pandas as pd
+import matplotlib.pyplot as plt
+from sklearn.cluster import KMeans
+from scipy import stats
+import seaborn as sns
+
+
+def make_map():
+    data = pd.read_csv('example/out.tips')
```
Comment (zorian15) [inline clustering.py:10]: Perhaps it would be useful here to make this more flexible -- so that we can cluster any `.tips` file?
We can do this with an argument parser like [`argparse`](https://docs.python.org/3/library/argparse.html) to do this pretty quickly.

File: clustering.py [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+
+    data = data[["ag1", "ag2"]]
+    # data = stats.zscore(data)
+
+    kmeans = KMeans(n_clusters=11, n_init=40, max_iter=100, random_state=0).fit(data)
```
Comment (zorian15) [inline clustering.py:15]: The arguments for `KMeans()` could also be specified in this argument parser as well. It would be smart to leave some defaults though for `n_init`, `max_iter` and `random_state`.

File: clustering.py [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+    sns.lmplot(x='ag1', y='ag2',
+               data=data,
+               fit_reg=False,
+               hue="clusters",
+               scatter_kws={"marker": "D",
+                            "s": 7})
+    plt.title('Map Clusters')
+    plt.xlabel('ag1')
+    plt.ylabel('ag2')
+    plt.savefig('mapClustersSklearn.png', bbox_inches='tight')
```
Comment (zorian15) [inline clustering.py:32]: Another thing that could be added to the argument parser (i.e., `out_path`)

**Review by zorian15 — CHANGES_REQUESTED** [review]
Nice Python code here @thienktran -- my main thing was suggesting something like an [argument parser](https://docs.python.org/3/library/argparse.html) to make it easier to try different hyperparameters and file paths when we run this script.

File: Simulation.java (hunk 1 above)
Comment (thienktran) [reply Simulation.java:479]: No, it's not needed to perform the clustering. We're using out.tips which it's already in csv format.

At first, I thought we were using out.timerseries to performing the clustering. It wasn't in csv format, so that's why I wrote this method.

File: clustering.py (hunk 2 above)
Comment (thienktran) [reply clustering.py:10]: I'll get started on this. Great suggestion!

File: Simulation.java (hunk 1 above)
Comment (zorian15) [reply Simulation.java:479]: ohh got it! thanks!

Comment (thienktran) [reply Simulation.java:479]: I just realized this method is actually needed to resolve this [issue](https://github.com/trvrb/antigen/issues/22)!

**Review by zorian15 — APPROVED** [review]
thanks for addressing the changes @thienktran -- and really awesome Python code! I think this is ready to merge into `main`
